### ISSUE TITLE
Tokens aren't compared

### ISSUE THREAD

**Issue by Dot-Rar** [lucko/BungeeGuard#9]
Players are able to connect to Spigot servers running BungeeGuard using a random token.

The Spigot server is running BungeeGuard and has this configuration:

```yaml
# BungeeGuard Configuration

# Allowed authentication tokens.
allowed-tokens:
  - "A2..."


# Messages
no-data-kick-message: "&cUnable to authenticate - no data was forwarded by the proxy."
no-properties-kick-message: "&cUnable to authenticate."
invalid-token-kick-message: "&cAn invalid authentication token was provided."
```

For obvious reasons, I have only showed the first 2 characters of the token.

I set up a BungeeCord server on my PC and installed BungeeGuard. Here's the token.yml:

```yaml
token: IwBuuaNiAxPMtFOKEkHRb2YmsSiMqZSrlFcVV2fY0baKWIKelcQwqBNq9NETdpgc
```

(Yes, I know the full token is there. I set this up for testing and won't be using it again). Obviously, the 2 tokens are completely different. However, BungeeGuard still allows me to enter ingame. Here's my BungeeCord configuration:

```yaml
inject_commands: false
forge_support: false
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
timeout: 30000
log_commands: false
online_mode: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: <censored>
    restricted: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
ip_forward: true
network_compression_threshold: 256
prevent_proxy_connections: false
groups:
  Perkelle:
  - admin
connection_throttle: 4000
stats: f41f3523-11fe-46e6-9cdd-1fe59ac6d060
connection_throttle_limit: 3
log_pings: true
```
